### ISSUE TITLE
Native memory leak

### ISSUE THREAD

**Issue by lochri** [x-stream/xstream#149]
Each time XML is being parsed a ZipFile instance is being kept inside the ClassLoader, even if it is alway the same Classes being deserialized.
This is the stacktrace of the Inflater being kept open:

java.base/java.util.zip.Inflater.<init>(Inflater.java:139)
	at java.base/java.util.zip.ZipFile$CleanableResource.getInflater(ZipFile.java:744)
	at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.<init>(ZipFile.java:438)
	at java.base/java.util.zip.ZipFile.getInputStream(ZipFile.java:405)
	at java.base/java.util.jar.JarFile.getBytes(JarFile.java:798)
	at java.base/java.util.jar.JarFile.checkForSpecialAttributes(JarFile.java:1005)
	at java.base/java.util.jar.JarFile.isMultiRelease(JarFile.java:388)
	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:507)
	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
	at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.getArchiveEntry(AbstractSingleArchiveResourceSet.java:97)
	at org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:262)
	at org.apache.catalina.webresources.StandardRoot.getResourcesInternal(StandardRoot.java:327)
	at org.apache.catalina.webresources.CachedResource.validateResources(CachedResource.java:140)
	at org.apache.catalina.webresources.Cache.getResources(Cache.java:129)
	at org.apache.catalina.webresources.StandardRoot.getResources(StandardRoot.java:315)
	at org.apache.catalina.webresources.StandardRoot.getClassLoaderResources(StandardRoot.java:231)
	at org.apache.catalina.loader.WebappClassLoaderBase.findResources(WebappClassLoaderBase.java:957)
	at java.base/java.lang.ClassLoader.getResources(ClassLoader.java:1466)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1195)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
	at java.xml/javax.xml.parsers.FactoryFinder$1.run(FactoryFinder.java:287)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.xml/javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:283)
	at java.xml/javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:261)
	at java.xml/javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:147)
	at org.jdom.input.JAXPParserFactory.createParser(JAXPParserFactory.java:125)
	at jdk.internal.reflect.GeneratedMethodAccessor633.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jdom.input.SAXBuilder.createParser(SAXBuilder.java:616)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:489)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:946)
	at com.thoughtworks.xstream.io.xml.JDomDriver.createReader(JDomDriver.java:59)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1085)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1076)

**Comment by joehni** [comment]
Sorry, but I don't see, how this is a problem of XStream. Not even of JDom. All it does is to use the Java SPI to look for an available SAXParserFactory implementation, which in turn scans the JARs on the classpath. So you either have a problem with your Tomcat version or the Java runtime.
