### ISSUE TITLE
Invalid Rererence

### ISSUE THREAD

**Issue by metalpalo** [x-stream/xstream#150]
Hi guys,
I have following problem when switching from version 1.4.9 to 1.4.10. Data serialized with old one cannot be deserialized with new one. 
Concretely old one puts something like:
`<transitionDate reference="../../creationDate"/>` 
and new one doesn't reuse reference and always creates like this:
`<transitionDate>2019-05-17T15:39:55.548</transitionDate>`

Problem is that I already have data generated by both version. Is possible to read old data with newer version.
I got following error:
`com.thoughtworks.xstream.converters.ConversionException: Invalid reference
---- Debugging information ----
message             : Invalid reference
reference           : ../../creationDate
referenced-type     : java.time.LocalDateTime
referenceable       : false

at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:58) ~[xstream-1.4.10.jar!/:1.4.10]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:503)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:429)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:503)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflec...`

thanks

**Comment by joehni** [comment]
Immutable types are not referenceable by default, but you can overwrite it:

```Java
xstream.addImmutableType(LocalDateTime.class, true);
```
