### ISSUE TITLE
Cannot deserialize object with new readObject()/writeObject() methods - When porting from 1.4.2 to 1.4.11.1

### ISSUE THREAD

**Issue by yccheok** [x-stream/xstream#179]
We are in the process of porting XStream 1.4.2 to 1.4.11.1.

We encountered the following problem during the porting https://github.com/x-stream/xstream/issues/178 . We manage to solve it using `implements Serializable`.

Now, we encounter the following crash.

```
com.thoughtworks.xstream.converters.ConversionException: Cannot deserialize object with new readObject()/writeObject() methods
---- Debugging information ----
message             : Cannot deserialize object with new readObject()/writeObject() methods
class               : org.yccheok.jstock.analysis.StockRelativeHistoryOperator
required-type       : org.yccheok.jstock.analysis.StockRelativeHistoryOperator
converter-type      : com.thoughtworks.xstream.converters.reflection.SerializableConverter
path                : /org.yccheok.jstock.analysis.OperatorIndicator/operators/org.yccheok.jstock.analysis.StockRelativeHistoryOperator
line number         : 3
class[1]            : java.util.ArrayList
required-type[1]    : java.util.ArrayList
converter-type[1]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
class[2]            : org.yccheok.jstock.analysis.OperatorIndicator
required-type[2]    : org.yccheok.jstock.analysis.OperatorIndicator
converter-type[2]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
version             : 1.4.11.1
-------------------------------
	at com.thoughtworks.xstream.converters.reflection.SerializableConverter.doUnmarshal(SerializableConverter.java:318)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:277)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readBareItem(AbstractCollectionConverter.java:132)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:117)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.addCurrentElementToCollection(CollectionConverter.java:98)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:91)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:85)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:80)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:499)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:425)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:277)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1487)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1467)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1338)
	at org.yccheok.jstock.gui.Utils.fromXML(Utils.java:1807)
```

This XML file (https://gist.github.com/yccheok/e76e91096ca839a20072d3ba3ed62113) is written by old 1.4.2.

Our data class is located at https://github.com/yccheok/jstock/tree/master/src/org/yccheok/jstock/analysis

Any hint on what's went wrong, and how can we resolve this?

Thanks.

**Comment by joehni** [comment]
Well, adding the Serialization interface modifies the XML layout. However, you did this, because you assumed that XStream had originally called readObject() of child and parent class ... which it never did.

See my following test class:
```java
public class Regression {
    public static class Parent {
        private void writeObject(ObjectOutputStream out) throws IOException {
            out.defaultWriteObject();
            System.out.println("Parent writeObject");
        }

        private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
            in.defaultReadObject();
            System.out.println("Parent readObject");
        }

        private Object readResolve() {
            System.out.println("Parent readResolve");
            return this;
        }
    }

    public static class Child extends Parent {
        private void writeObject(ObjectOutputStream out) throws IOException {
            out.defaultWriteObject();
            System.out.println("Child writeObject");
        }

        private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
            in.defaultReadObject();
            System.out.println("Child readObject");
        }

        private Object readResolve() {
            System.out.println("Child readResolve");
            return this;
        }
    }

    public static void main(String[] args) {
        XStream xstream = new XStream();
        System.out.println("== Serialization ==");
        String xml = xstream.toXML(new Child());
        System.out.println(xml);
        System.out.println("== Deserialization ==");
        xstream.fromXML(xml);
        System.out.println("===============");
    }
}
```

I compiled it with Java 8 and created following directory structure:
```
$ find . -type f
./xmlpull-1.1.3.1.jar
./xpp3_min-1.1.4c.jar
./xstream-1.4.jar
./xstream-1.4.9.jar
./xstream-1.4.8.jar
./xstream-1.4.7.jar
./xstream-1.4.6.jar
./xstream-1.4.5.jar
./xstream-1.4.4.jar
./xstream-1.4.3.jar
./xstream-1.4.2.jar
./xstream-1.4.11.jar
./xstream-1.4.11.1.jar
./xstream-1.4.10.jar
./xstream-1.4.1.jar
./xstream-1.3.jar
./xstream-1.3.1.jar
./xstream-1.2.2.jar
./xstream-1.2.1.jar
./classes/Regression.class
./classes/Regression$Parent.class
./classes/Regression$Child.class
```

The following call definitely shows, that I am right:

```
$ for a in xstream-*.jar; do echo -e "$a"; java -cp $a:xpp3_min-1.1.4c.jar:xmlpull-1.1.3.1.jar:classes Regression; done
xstream-1.2.1.jar
== Serialization ==
<Regression_-Child/>
== Deserialization ==
Child readResolve
===============
xstream-1.2.2.jar
== Serialization ==
<Regression_-Child/>
== Deserialization ==
Child readResolve
===============
xstream-1.3.1.jar
== Serialization ==
<Regression_-Child/>
== Deserialization ==
Child readResolve
===============
xstream-1.3.jar
== Serialization ==
<Regression_-Child/>
== Deserialization ==
Child readResolve
===============
xstream-1.4.1.jar
== Serialization ==
<Regression_-Child/>
== Deserialization ==
Child readResolve
===============
xstream-1.4.10.jar
== Serialization ==
<Regression_-Child/>
== Deserialization ==
Security framework of XStream not initialized, XStream is probably vulnerable.
Child readResolve
===============
xstream-1.4.11.1.jar
== Serialization ==
<Regression_-Child/>
== Deserialization ==
Security framework of XStream not initialized, XStream is probably vulnerable.
Child readResolve
===============
xstream-1.4.11.jar
== Serialization ==
<Regression_-Child/>
== Deserialization ==
Security framework of XStream not initialized, XStream is probably vulnerable.
Child readResolve
===============
xstream-1.4.2.jar
== Serialization ==
<Regression_-Child/>
== Deserialization ==
Child readResolve
===============
xstream-1.4.3.jar
== Serialization ==
<Regression_-Child/>
== Deserialization ==
Child readResolve
===============
xstream-1.4.4.jar
== Serialization ==
<Regression_-Child/>
== Deserialization ==
Child readResolve
===============
xstream-1.4.5.jar
== Serialization ==
<Regression_-Child/>
== Deserialization ==
Child readResolve
===============
xstream-1.4.6.jar
== Serialization ==
<Regression_-Child/>
== Deserialization ==
Child readResolve
===============
xstream-1.4.7.jar
== Serialization ==
<Regression_-Child/>
== Deserialization ==
Child readResolve
===============
xstream-1.4.8.jar
== Serialization ==
<Regression_-Child/>
== Deserialization ==
Child readResolve
===============
xstream-1.4.9.jar
== Serialization ==
<Regression_-Child/>
== Deserialization ==
Child readResolve
===============
xstream-1.4.jar
== Serialization ==
<Regression_-Child/>
== Deserialization ==
Child readResolve
===============
```

XStream has never called readObject for types that do not implement Serializable. Definitely.

So my advice: Revert your changes to the classes and serialize your objects (if possible with the same data) once with 1.4.2 and once with 1.4.11.1 and look at the difference in the XML structure. That might give a hint...

**Comment by yccheok** [comment]
You're right!

After seeing your posted example, and tested with a simple project in old 1.4.2, seem like Parent's (without Serializable) `readResolve` will not be called.

But, to my surprise, in my complete project, all these years it is being called without issue. I have totally no idea why...
