### ISSUE TITLE
Lots of NoSuchFieldExceptions when serializing objects

### ISSUE THREAD

**Issue by AndProhaska** [x-stream/xstream#235]
Hi!

While looking at thread dumps during XStream serialization we saw that a lof of NoSuchFieldExceptions happen. The exceptions happen while trying to find the class that actually declares a field in the hierarchy of classes. The Java VM obviously spends a lot of time in filling in those stacktraces. We made thread dumps several times.

```
        at java.lang.Throwable.fillInStackTrace(Native Method)
        at java.lang.Throwable.fillInStackTrace(Throwable.java:784)
        - locked <0x00000006d9d533b0> (a java.lang.NoSuchFieldException)
        at java.lang.Throwable.<init>(Throwable.java:266)
        at java.lang.Exception.<init>(Exception.java:66)
        at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:56)
        at java.lang.NoSuchFieldException.<init>(NoSuchFieldException.java:50)
        at java.lang.Class.getDeclaredField(Class.java:2070)
        at com.thoughtworks.xstream.mapper.ImplicitCollectionMapper.getMapper(ImplicitCollectionMapper.java:45)
        at com.thoughtworks.xstream.mapper.ImplicitCollectionMapper.getImplicitCollectionDefForFieldName(ImplicitCollectionMapper.java:92)
        at com.thoughtworks.xstream.mapper.MapperWrapper.getImplicitCollectionDefForFieldName(MapperWrapper.java:74)
        at com.thoughtworks.xstream.mapper.MapperWrapper.getImplicitCollectionDefForFieldName(MapperWrapper.java:74)
        at com.thoughtworks.xstream.mapper.MapperWrapper.getImplicitCollectionDefForFieldName(MapperWrapper.java:74)
        at com.thoughtworks.xstream.mapper.MapperWrapper.getImplicitCollectionDefForFieldName(MapperWrapper.java:74)
        at com.thoughtworks.xstream.mapper.MapperWrapper.getImplicitCollectionDefForFieldName(MapperWrapper.java:74)
        at com.thoughtworks.xstream.mapper.MapperWrapper.getImplicitCollectionDefForFieldName(MapperWrapper.java:74)
        at com.thoughtworks.xstream.mapper.MapperWrapper.getImplicitCollectionDefForFieldName(MapperWrapper.java:74)
        at com.thoughtworks.xstream.mapper.MapperWrapper.getImplicitCollectionDefForFieldName(MapperWrapper.java:74)
        at com.thoughtworks.xstream.mapper.MapperWrapper.getImplicitCollectionDefForFieldName(MapperWrapper.java:74)
        at com.thoughtworks.xstream.mapper.MapperWrapper.getImplicitCollectionDefForFieldName(MapperWrapper.java:74)
        at com.thoughtworks.xstream.mapper.MapperWrapper.getImplicitCollectionDefForFieldName(MapperWrapper.java:74)
        at com.thoughtworks.xstream.mapper.MapperWrapper.getImplicitCollectionDefForFieldName(MapperWrapper.java:74)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.<init>(AbstractReflectionConverter.java:152)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:144)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
```

Looking at the code it seems that this is intended behaviour in the ImplicitCollectionMapper. But looking a little bit further it seems that XStream actually wants to cache the result of which field is declared in which class. But to me it looks like a simple check is wrong and causes XStream not to use the cache at all. In the AbstractReflectionConverter around line 198 there is a code

```
                final Field defaultField = defaultFieldDefinition.get(info.fieldName);
                Mapper.ImplicitCollectionMapping mapping = mapper.getImplicitCollectionDefForFieldName(defaultField
                    .getDeclaringClass() == info.definedIn ? sourceType : info.definedIn, info.fieldName);
```

But shouldn't this be?

```
                final Field defaultField = defaultFieldDefinition.get(info.fieldName);
                Mapper.ImplicitCollectionMapping mapping = mapper.getImplicitCollectionDefForFieldName(defaultField
                    .getDeclaringClass() == info.definedIn ? info.definedIn : sourceType, info.fieldName);
```

**Comment by joehni** [comment]
No, this code is absolutely correct. It handles implicit collections and hidden fields. Make your change and run the unis tests if you do not believe.

**Comment by AndProhaska** [comment]
I do believe you. Something else must be happening here. This should be just ordinary java classes, no implicit collections or hidden fields.

**Comment by AndProhaska** [comment]
Just to finish this, I added an own MapperWrapper that caches the result of Mapper.getImplicitCollectionDefForFieldName().

**Comment by joehni** [comment]
Nevertheless, I have the impression, you're not using a current version of XStream.
