### ISSUE TITLE
Failed to deserialized Java 8 ZonedDateTime (JSON format)

### ISSUE THREAD

**Issue by simonwg** [x-stream/xstream#24]
If ZonedDateTime be used in JSON format, Xtream would fail in deserialization.

```
Exception in thread "main" com.thoughtworks.xstream.converters.ConversionException: java.lang.Byte cannot be cast to java.lang.Integer : java.lang.Byte cannot be cast to java.lang.Integer
---- Debugging information ----
message             : java.lang.Byte cannot be cast to java.lang.Integer
cause-exception     : java.lang.ClassCastException
cause-message       : java.lang.Byte cannot be cast to java.lang.Integer
class               : java.time.Ser
required-type       : java.time.Ser
converter-type      : com.thoughtworks.xstream.converters.reflection.ExternalizableConverter
path                : /map/entry/java.time.ZonedDateTime
line number         : -1
class[1]            : java.util.HashMap
converter-type[1]   : com.thoughtworks.xstream.converters.collections.MapConverter
version             : 1.4.8
-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:71)
	at com.thoughtworks.xstream.converters.collections.MapConverter.putCurrentEntryIntoMap(MapConverter.java:110)
	at com.thoughtworks.xstream.converters.collections.MapConverter.populateMap(MapConverter.java:98)
	at com.thoughtworks.xstream.converters.collections.MapConverter.populateMap(MapConverter.java:92)
	at com.thoughtworks.xstream.converters.collections.MapConverter.unmarshal(MapConverter.java:87)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1206)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1190)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1061)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1052)
```

Test Program:

```java
package test;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.json.JettisonMappedXmlDriver;
import java.time.ZonedDateTime;
import java.util.HashMap;
import java.util.Map;

public class TestXStreamSerialization {

    public static void main(String[] args) {
        XStream xstream = new XStream(new JettisonMappedXmlDriver());

        Map<String, Object> toBeSerializedMap = new HashMap<>();
        toBeSerializedMap.put("my_date", ZonedDateTime.now());

        String jsonStr = xstream.toXML(toBeSerializedMap);

        // print {"map":[{"entry":{"string":"my_date","java.time.ZonedDateTime":{"@resolves-to":"java.time.Ser","byte":[6,8,27,10,2,59,32,7],"int":[2015,639000000],"string":"Asia\/Shanghai"}}}]}
        System.out.println("JSON String: " + jsonStr);

        // throw exception here        
        Map<String, Object> map = (Map<String, Object>) xstream.fromXML(jsonStr);
    }
}
```

**Comment by joehni** [comment]
Hi, this is unfortunately beyond repair, see the word of warning in the [tutorial](http://x-stream.github.io/json-tutorial.html). Jettison is a StAX backend. XStream writes is data into a normal StAX writer, not knowing something about the result. Jettison tries now to generate something useful out of the events that produce normally XML, which would look like:

```XML
<java.time.ZonedDateTime resolves-to="java.time.Ser">
  <byte>6</byte>
  <int>2015</int>
  <byte>8</byte>
  <byte>28</byte>
  <byte>0</byte>
  <byte>13</byte>
  <byte>42</byte>
  <int>639000000</int>
  <byte>8</byte>
  <byte>7</byte>
  <string>Europe/Berlin</string>
</java.time.ZonedDateTime>
```
Since JSON cannot have two labels with the same name, Jettison generates arrays of the matching elements at the cost of the correct value sequence. This is fatal for a java.time.Ser at deserialization time.

What you can actually do is writing a custom converter for ZonedDateTime where the type is represented as String. Use this String representation to convert back into a ZonedDateTime instance.

**Comment by simonwg** [comment]
Thanks for your information

**Comment by BirkeHeeren** [comment]
I wrote a converter and registered it but it seems, that it is not used by xstream:
public class ZonedDateTimeConverter implements Converter
{
@Override
public boolean canConvert(Class type)
{
  return (type != null) && (ZonedDateTime.class.equals(type));
}
@Override
public void marshal(Object source, HierarchicalStreamWriter writer,
     MarshallingContext context)
{
  ZonedDateTime zonedDateTime = (ZonedDateTime) source;
  writer.setValue(zonedDateTime.format(DateTimeFormatter.ISO_OFFSET_DATE_TIME));  
}

@Override
public Object unmarshal(HierarchicalStreamReader reader,
     UnmarshallingContext context)
{
  return ZonedDateTime.parse(reader.getValue(), DateTimeFormatter.ISO_OFFSET_DATE_TIME);
}
}

The error I keep getting is: 

com.thoughtworks.xstream.converters.ConversionException: Cannot deserialize object with new readObject()/writeObject() methods

Debugging information
class               : java.time.ZonedDateTime
required-type       : java.time.ZonedDateTime
converter-type      : com.thoughtworks.xstream.converters.reflection.SerializableConverter
path                : /de.unigreifswald.floradb.importer.model.ImportJob/exportDate
line number         : 5
class[1]            : de.unigreifswald.floradb.importer.model.ImportJob
converter-type[1]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
version             : 1.4.6

**Comment by joehni** [comment]
You are trying to unmarshal from an existing XML written with a different converter. The JDK actually does not serialize instances of java.time.ZonedDateTime, but instances of java.time.Ser. However, why do you not use an actual version of XStream that contains the converters for the java.time package?
