### ISSUE TITLE
java.util.ConcurrentModificationException,xstream-1.4.16jar Concurrent processing is not supported？

### ISSUE THREAD

**Issue by siweicun** [x-stream/xstream#249]
cause-exception     : java.util.ConcurrentModificationException
cause-message       : null
-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:77)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1429)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1409)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1294)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1285)
Caused by: java.util.ConcurrentModificationException
	at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1100)
	at java.util.TreeMap$KeyIterator.next(TreeMap.java:1154)
	at com.thoughtworks.xstream.core.util.PrioritizedList$PrioritizedItemIterator.next(PrioritizedList.java:91)
	at com.thoughtworks.xstream.core.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:73)
	at com.thoughtworks.xstream.XStream$1.lookupConverterForType(XStream.java:483)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:56)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:397)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:277)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)

**Comment by siweicun** [comment]
xstream底层使用的TreeMap

**Comment by joehni** [comment]
Hi,

yes it is safe for concurrent processing. But as your said just for *processing*, see [Life Cycle in the architecture document](https://x-stream.github.io/architecture.html#LifeCycle) and in the [FAQ](https://x-stream.github.io/faq.html#Scalability). If you change XStream's configuration, while you are processing, you will get such exceptions. And note, that processing annotations on-the-fly qualifies as configuring while processing, the limitations are [explicitly documented](https://x-stream.github.io/annotations-tutorial.html#AutoDetect). Preprocess your annotations instead.

Regards,
Jörg
