### ISSUE TITLE
java.lang.ClassNotFoundException: com.thoughtworks.xstream.mapper.EnumMapper

### ISSUE THREAD

**Issue by harvanchik** [x-stream/xstream#252]
Error: 

```java
[16:57:19 WARN]: com.thoughtworks.xstream.InitializationException: Could not instantiate mapper : com.thoughtworks.xstream.mapper.EnumMapper
[16:57:19 WARN]:        at com.thoughtworks.xstream.XStream.buildMapperDynamically(XStream.java:604)
[16:57:19 WARN]:        at com.thoughtworks.xstream.XStream.buildMapper(XStream.java:576)
[16:57:19 WARN]:        at com.thoughtworks.xstream.XStream.<init>(XStream.java:547)
[16:57:19 WARN]:        at com.thoughtworks.xstream.XStream.<init>(XStream.java:481)
[16:57:19 WARN]:        at com.thoughtworks.xstream.XStream.<init>(XStream.java:455)
[16:57:19 WARN]:        at com.thoughtworks.xstream.XStream.<init>(XStream.java:408)
[16:57:19 WARN]:        at com.thoughtworks.xstream.XStream.<init>(XStream.java:356)
[16:57:19 WARN]:        at com.blockeyhockey.plugin.BlockeyHockey.testXML(BlockeyHockey.java:130)
[16:57:19 WARN]:        at com.blockeyhockey.plugin.BlockeyHockey.onEnable(BlockeyHockey.java:49)
[16:57:19 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:57:19 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[16:57:19 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[16:57:19 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[16:57:19 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[16:57:19 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:582)
[16:57:19 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:292)
[16:57:19 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1061)
[16:57:19 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[16:57:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[16:57:19 WARN]: Caused by: java.lang.ClassNotFoundException: com.thoughtworks.xstream.mapper.EnumMapper
[16:57:19 WARN]:        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
[16:57:19 WARN]:        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
[16:57:19 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[16:57:19 WARN]:        at com.thoughtworks.xstream.core.util.CompositeClassLoader.loadClass(CompositeClassLoader.java:146)
[16:57:19 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[16:57:19 WARN]:        at java.base/java.lang.Class.forName(Class.java:398)
[16:57:19 WARN]:        at com.thoughtworks.xstream.XStream.buildMapperDynamically(XStream.java:600)
[16:57:19 WARN]:        ... 18 more
```

pom.xml dependency:

```xml
<dependency>
    <groupId>com.thoughtworks.xstream</groupId>
    <artifactId>xstream</artifactId>
    <version>1.4.16</version>
</dependency>
```

Code running on launch:

```java
private void testXML() {
    try {
        File file = new File(this.getDataFolder(), "rinks/basic.xml");
        XStream xStream = new XStream();
        xStream.processAnnotations(Rink2.class);
        Rink2 rink = (Rink2) xStream.fromXML(file);
        System.out.println(rink.getName() + " - " + rink.getDescription());
    } catch (Exception e) {
        e.printStackTrace();
    }
}
```

EnumMapper.class missing:

![image](https://user-images.githubusercontent.com/66141166/116795013-8e9e2300-aa86-11eb-8ecf-9259ebc35a0f.png)

**Comment by joehni** [comment]
I don't know, where you got this version from, but go to Maven central and download it and you'll see that it is part of the jar.

**Comment by harvanchik** [comment]
> I don't know, where you got this version from, but go to Maven central and download it and you'll see that it is part of the jar.

I got it from here.  This is wrong? https://mvnrepository.com/artifact/com.thoughtworks.xstream/xstream/1.4.16

**Comment by harvanchik** [comment]
I do see it when downloading the `jar`, but why is it missing when using Maven?  I'd prefer to use Maven.

![image](https://user-images.githubusercontent.com/66141166/116798040-b13d3580-aaa0-11eb-8def-bb4e3a6778c7.png)

**Comment by joehni** [comment]
Well, Maven connects to Maven central and the jar contains the class. Try to delete your local repo to force Maven to download it again.

**Comment by joehni** [comment]
Sorry, I missed the error message. Java finds the class, but it cannot be initialized. You have to put xstream in the classpath, it won't work in the module path.

**Comment by harvanchik** [comment]
> Sorry, I missed the error message. Java finds the class, but it cannot be initialized. You have to put xstream in the classpath, it won't work in the module path.

I am building my `jar` using maven.  What do I have to change about my original `pom.xml` to make this change?

**Comment by harvanchik** [comment]
I do not understand why `EnumMapper` is not being included in my `jar` file.  You can see I have it as a dependency in my `pom.xml` and EnumMapper can be seen on the left side under External Libraries for this project.  But it is missing when I `mvn package` it.  Why?

![image](https://user-images.githubusercontent.com/66141166/116799262-aee0d880-aaac-11eb-9908-bdf2afb7ca92.png)

**Comment by joehni** [comment]
What do the class files of xstream.jar in your jar at all? Sorry, I don't know what you do to build your jar file, but as you've shown on the screenshot, nothis is wrong with the xstream.jar.

**Comment by harvanchik** [comment]
I use `mvn package` to build the `jar`. See my `pom.xml` in a post above.

**Comment by harvanchik** [comment]
![image](https://user-images.githubusercontent.com/66141166/116819905-2c492f00-ab27-11eb-8246-a23e2bc5a201.png)

![image](https://user-images.githubusercontent.com/66141166/116819909-353a0080-ab27-11eb-830f-8138be830393.png)

**Comment by joehni** [comment]
What does this all have to do with XStream or even Maven? You have configured Maven to use the shade plugin to run in Maven's package phase. It is your setup instructing the shade plugin to drop anything it assumes that is not required. Obviously this does not work as you expect. XStream loads a lot of classes dynamically.

**Comment by harvanchik** [comment]
Okay.  I had no clue that the shade plugin would make those assumptions.  Is there anything I can do to configure the shade plugin to not make assumptions like that?

**Comment by joehni** [comment]
Well, we can both read the documentation to Maven's Shade plugin. The question is, why should I? ;-)
