### ISSUE TITLE
Fails on Java 16 for java.util.Arrays$ArrayList and java.util.Collections$EmptyList

### ISSUE THREAD

**Issue by famod** [x-stream/xstream#253]
Over at [Quarkus](https://github.com/quarkusio/quarkus) (see also https://github.com/quarkusio/quarkus/issues/17091), I had to disable two test classes for the JDK 16 CI job due to:

Conversions fails for `Arrays.asList(...)`:
```
com.thoughtworks.xstream.converters.ConversionException:
No converter available
---- Debugging information ----
message             : No converter available
type                : java.util.Arrays$ArrayList
converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[1]          : Unable to make field protected transient int java.util.AbstractList.modCount accessible: module java.base does not "opens java.util" to unnamed module @2a79781f
-------------------------------
        at com.thoughtworks.xstream.core.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:78)
        at com.thoughtworks.xstream.XStream$1.lookupConverterForType(XStream.java:543)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:50)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:269)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:173)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:92)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:269)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:173)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:92)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:44)
        at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:81)
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:41)
        at com.thoughtworks.xstream.XStream.marshal(XStream.java:1198)
        at com.thoughtworks.xstream.XStream.marshal(XStream.java:1187)
        at com.thoughtworks.xstream.XStream.toXML(XStream.java:1159)
        at com.thoughtworks.xstream.XStream.toXML(XStream.java:1145)
```

Conversions fails for `Collections.emptyList()`:
```
com.thoughtworks.xstream.converters.ConversionException:
No converter available
---- Debugging information ----
message             : No converter available
type                : java.util.Collections$EmptyList
converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[1]          : Unable to make field protected transient int java.util.AbstractList.modCount accessible: module java.base does not "opens java.util" to unnamed module @2a79781f
-------------------------------
        at com.thoughtworks.xstream.core.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:78)
        at com.thoughtworks.xstream.XStream$1.lookupConverterForType(XStream.java:543)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:50)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:269)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:173)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:92)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:269)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:173)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:92)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:44)
        at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:81)
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:41)
        at com.thoughtworks.xstream.XStream.marshal(XStream.java:1198)
        at com.thoughtworks.xstream.XStream.marshal(XStream.java:1187)
        at com.thoughtworks.xstream.XStream.toXML(XStream.java:1159)
        at com.thoughtworks.xstream.XStream.toXML(XStream.java:1145)
```

This is with 1.4.16 and current 1.5.0-SNAPSHOT.

PS: I suppose there is a strong connection to #101.

**Comment by famod** [comment]
Btw, if I use Java 9+ `List.of(...)` instead of `Arrays.asList(...)` I'm getting:

```
com.thoughtworks.xstream.converters.ConversionException:
No converter available
---- Debugging information ----
message             : No converter available
type                : java.util.ImmutableCollections$List12
converter           : com.thoughtworks.xstream.converters.reflection.SerializableConverter
message[1]          : Unable to make private void java.util.ImmutableCollections$List12.readObject(java.io.ObjectInputStream) throws java.io.IOException,java.lang.ClassNotFoundException accessible: module java.base does not "opens java.util" to unnamed module @2a79781f
converter[1]        : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[2]          : Unable to make field private final java.lang.Object java.util.ImmutableCollections$List12.e0 accessible: module java.base does not "opens java.util" to unnamed module @2a79781f
-------------------------------
```

Workaround for this is `new ArrayList<>(List.of(...))` and workaround for `Collections.emptyList()` is `new ArrayList<>()`.

**Comment by joehni** [comment]
Hi,

well, none of this fails (XStream has unit tests for these types running with Java 16), but you have to run XStream in the classpath. I guess, this is not an option for Quarkus. However, the workaround does not produce objects with same behaviour after deserialization. An empty list where you can add objects after deserialization might cause some other surprises.

**Comment by famod** [comment]
Hi and thanks for your feedback!

> well, none of this fails

Depends on your POV, but I'm getting a `ConversionException` while trying to marshal so... 🤷 

> but you have to run XStream in the classpath

Might be a bit too late for me but I'm not fully sure what that means. There is some classloader juggling in Quarkus but nevertheless XStream is "on the classpath". What am I missing?

>  However, the workaround does not produce objects with same behaviour after deserialization. An empty list where you can add objects after deserialization might cause some other surprises.

Of course you are right.

**Comment by joehni** [comment]
> Depends on your POV

Look at the CI results, if you do not believe it:
- com.thoughtworks.acceptance.CollectionTest.testEmptyList
- com.thoughtworks.acceptance.CollectionTest.testListFromArrayAsList

You run XStream in the ModulePath and Java's module system does not allow XStream to access the internals of the referenced classes.

**Comment by joehni** [comment]
For Java 16 you'll need option --illegal-access=permit

**Comment by famod** [comment]
Will this be a requirement also for xstream 1.5?

**Comment by xeruf** [comment]
Shouldn't this flag also work?

    --add-opens=java.base/java.util=ALL-UNNAMED

**Comment by shoomi** [comment]
> @xeruf Thanks. I don't compile, just execute. I got it to work using the following JVM parameters indeed: `--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED`
> 
> Thanks!

It works for me!

**Comment by joehni** [comment]
As you already have noticed, starting with Java 17 you will have to open the modules, which will work also for the older Java versions instead of the --illegal-access option (that no longer exists with Java 17).

**Comment by kirank1991** [comment]
I am still getting the below error with Xstream . any solution to this ?
{message=No converter available, type=java.util.Collections$UnmodifiableSet, converter=com.thoughtworks.xstream.converters.reflection.ReflectionConverter, message[1]=Unable to make field private static final long java.util.Collections$UnmodifiableCollection.serialVersionUID accessible: module java.base does not "opens java.util" to unnamed module @76c3e77a}
