### ISSUE TITLE
xStream fails with org.apache.commons.collections.bidimap.DualHashBidiMap

### ISSUE THREAD

**Issue by vipul79321** [x-stream/xstream#257]
xStream fails to properly serialize and deserialize DualHashBidiMap objects. [Link to google group conversation](https://groups.google.com/g/xstream-user/c/GwKhv9F-6ac)

It throws error on running the below code - 
```java
DualHashBidiMap db = new DualHashBidiMap();
db.put(1,2);
XStream xStream=new XStream(new DomDriver());
String xml = xStream.toXML(db);
DualHashBidiMap db2 = (DualHashBidiMap)xStream.fromXML(xml);
```

Generated XML is as follows - 
```xml
<org.apache.commons.collections.bidimap.DualHashBidiMap serialization="custom">
<unserializable-parents/>
<org.apache.commons.collections.bidimap.DualHashBidiMap>
<default/>
<map>
<entry>
<int>1</int>
<int>2</int>
</entry>
</map>
</org.apache.commons.collections.bidimap.DualHashBidiMap>
```

While deserializing above XML, following error is thrown - 
```java
Security framework of XStream not explicitly initialized, using predefined black list on your own risk.
com.thoughtworks.xstream.converters.ConversionException: Failed calling method
---- Debugging information ----
message : Failed calling method
cause-exception : java.lang.NullPointerException
cause-message : null
method : org.apache.commons.collections.bidimap.DualHashBidiMap.readObject()
class : org.apache.commons.collections.bidimap.DualHashBidiMap
required-type : org.apache.commons.collections.bidimap.DualHashBidiMap
converter-type : com.thoughtworks.xstream.converters.reflection.SerializableConverter
path : /org.apache.commons.collections.bidimap.DualHashBidiMap/org.apache.commons.collections.bidimap.DualHashBidiMap
version : 1.4.17
at com.thoughtworks.xstream.core.util.SerializationMembers.callReadObject(SerializationMembers.java:136)
at com.thoughtworks.xstream.converters.reflection.SerializableConverter.doUnmarshal(SerializableConverter.java:443)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:277)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1431)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1411)
at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1296)
at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1287)
at com.xyz.main.SerializerMain.normalserialization(SerializerMain.java:131)
at com.xyz.main.SerializerMain.main(SerializerMain.java:65)
Caused by: java.lang.NullPointerException
at org.apache.commons.collections.bidimap.DualHashBidiMap.readObject(DualHashBidiMap.java:101)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at com.thoughtworks.xstream.core.util.SerializationMembers.callReadObject(SerializationMembers.java:132)
```
Best,
Vipul

**Comment by joehni** [comment]
Unfortunately there's not much XStream can do here. Java Serialization actually violates the specification of the VM, since it calls for a serializable object the constructor of the non-serializable parent only. There is no possibility to do the same with Java code (or any other code running on a VM).

Since any workaround has other unwanted side effects or more severe restrictions, the best option is to handle such types with a custom converter.
