### ISSUE TITLE
XStream 1.4.17 the high concurrency can lead to CPU 100%

### ISSUE THREAD

**Issue by joakapp** [x-stream/xstream#266]
exception:

"catalina-exec-32" #27647 daemon prio=5 os_prio=0 tid=0x00007fe7a801e000 nid=0xb36c runnable [0x00007fe745a5b000]
   java.lang.Thread.State: RUNNABLE
	at java.util.TreeMap.put(TreeMap.java:568)
	at java.util.TreeSet.add(TreeSet.java:255)
	at com.thoughtworks.xstream.core.util.PrioritizedList.add(PrioritizedList.java:40)
	at com.thoughtworks.xstream.core.DefaultConverterLookup.registerConverter(DefaultConverterLookup.java:65)
	at com.thoughtworks.xstream.XStream.registerConverter(XStream.java:1290)
	at com.thoughtworks.xstream.XStream.registerConverter(XStream.java:1285)

OS:
   
   Redhat 7.7/  MySQL 5.7.24 / cpu 8 process / mem 16G

**Comment by joehni** [comment]
XStream has two phases, first the configuration phase, then the marshalling/unmarshalling phase. The registerConverter is part of the XStream configuration phase which is not, has been never and will never be safe for multithreading. If your application uses concurrent calls in this phase, your usage of XStream is fundamentally flawed.

**Comment by joakapp** [comment]
Thanks !
