### ISSUE TITLE
1.4.18 version breaking JMapper with com.thoughtworks.xstream.security.ForbiddenClassException: com.googlecode.jmapper.xml.beans.XmlJmapper 

### ISSUE THREAD

**Issue by injulkarnilesh** [x-stream/xstream#270]
Even though JMapper has a dependency on XStream:1.4.9 it had been working fine with XStream until 1.4.17 and it is right to assume it to work with patch version upgrades. 
But recent 1.4.18 is breaking the JMapper with exception as: 

    com.googlecode.jmapper.exceptions.JMapperException: com.thoughtworks.xstream.security.ForbiddenClassException: 
    com.googlecode.jmapper.xml.beans.XmlJmapper
	at com.googlecode.jmapper.config.JmapperLog.error(JmapperLog.java:46)
	at com.googlecode.jmapper.JMapper.<init>(JMapper.java:437)
	at com.googlecode.jmapper.JMapper.<init>(JMapper.java:412)
    Caused by: com.thoughtworks.xstream.security.ForbiddenClassException: com.googlecode.jmapper.xml.beans.XmlJmapper
	at com.thoughtworks.xstream.security.NoTypePermission.allows(NoTypePermission.java:26)
	at com.thoughtworks.xstream.mapper.SecurityMapper.realClass(SecurityMapper.java:74)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
	at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:47)
	at com.thoughtworks.xstream.core.util.HierarchicalStreams.readClassType(HierarchicalStreams.java:29)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:133)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1391)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1376)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1270)
	at com.googlecode.jmapper.util.FilesManager.toXmlJmapper(FilesManager.java:1048)
	at com.googlecode.jmapper.util.FilesManager.readAtRuntime(FilesManager.java:1035)
	at com.googlecode.jmapper.xml.XML.<init>(XML.java:66)
	at com.googlecode.jmapper.xml.XmlBuilder.atRuntime(XmlBuilder.java:44)
	at com.googlecode.jmapper.generation.MapperBuilder.generate(MapperBuilder.java:86)
	at com.googlecode.jmapper.JMapper.createMapper(JMapper.java:450)
	at com.googlecode.jmapper.JMapper.<init>(JMapper.java:432)
	... 29 more

This exception is thorwn while creating an instance of JMapper as

`final JMapper<User, Employee> jMapper = new JMapper<>(User.class, Employee.class, mappingXml);`

**Comment by joehni** [comment]
XStream is using now a whilelist by default (already recommended for nearly a decade now). A blacklist has always open security holes. You will have to setup XStream's Security Framework now also for your class types, see the documentation.

**Comment by injulkarnilesh** [comment]
Shouldn't this breaking change have been introduced as a major version change and not a patch version change?

**Comment by joehni** [comment]
That was the original intent: Keep the blacklist for 1.4.x and the whitelist for 1.5.x as default. However, in the last 12 months my complete spare time was consumed by maintaining this blacklist and writing CVE reports. This situation had to change. It is obviously now, that you cannot provide a secure XStream instance with a default blacklist. Especially since the blacklist contained only typed from the Java Runtime itself and none for the myriads of types in additional libraries, which might be used to manipulate an application also.

Since XStream has been offering a helper method for years to set up an instance with the same whitelist, which is used as default in 1.5.x, each for almost a decade had the opportunity to initialize the security framework itself. XStream 1.4.18 does not break any application that does initialize the Security Framework. Switching to 1.5.x would have meant more incoming security issues for 1.4.x and this was no longer maintainable.

If you don't care about security, you can stay with 1.4.17 (nothing else has really changed) or finally setup the Security Framework on your own with 1.4.18, but the responsibility to provide a secure application to your users is now yours.

**Comment by luismora1224** [comment]
Hello, I have this same problem, but with version 1.4.19, I have read the comments, however I cannot understand how to implement this solution of the security framework, I am using spring boot 2.7.0, there will be some guide or manual, that explain how to do this security framework in this framework. I imagine you should create a bean, where you put the configuration of the class or classes, which can be used, but I can't understand it well, thank you very much in advance.

**Comment by joehni** [comment]
The initialization of the [Security Framework](https://x-stream.github.io/security.html#framework) is documented. However, I have no clue what Spring does with it.

**Comment by jesperancinha** [comment]
I am facing the same issue on my project [video-series-app](https://gitlab.com/jesperancinha/video-series-app). I was using x-stream for my axon framework project, but since this update, everything is failing and I also still couldn't get it to work in Sring. I don't understand how Axon uses it or how Spring uses it, but I guess  I just want to say that the change is minor and I wouldn't expect this dramatic change to happen on a patch update. I will open an issue to them though because it seems this problem is going to be delegated to whoever is using x-stream.

**Comment by joehni** [comment]
> I wouldn't expect this dramatic change to happen on a patch update.

If the Axon Framework would have acted in the last decade and properly set up their security, nothing would have changed with this update.

**Comment by gklijs** [comment]
> If the Axon Framework would have acted in the last decade and properly set up their security, nothing would have changed with this update.

It's impossible to set the whitelist for users. But they can set it using something like:
```java
    @Bean
    public XStream xStream() {
        XStream xStream = new XStream();

        xStream.allowTypesByWildcard(new String[]{
                "java.util.**",
                "tech.gklijs.tech.**"
        });
        return xStream;
    }
```

**Comment by jesperancinha** [comment]
@gklijs, tks for your suggestion. It did not work for me yet though. I've posted you a response in the axon issue.
