### ISSUE TITLE
x-stream master branch fails to pass all tests

### ISSUE THREAD

**Issue by jtnord** [x-stream/xstream#283]
Windows 11 x64
```
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Java version: 1.8.0_265, vendor: AdoptOpenJDK, runtime: c:\Java\jdk-8.0.265.01-hotspot\jre
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

```
[ERROR] Tests run: 29, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 0.012 s <<< FAILURE! - in com.thoughtworks.xstream.io.xml.StaxReaderTest
[ERROR] testSupportsFieldsWithSpecialCharsInXml11(com.thoughtworks.xstream.io.xml.StaxReaderTest)  Time elapsed: 0.008 s  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<���???�> but was:<>
        at junit.framework.Assert.assertEquals(Assert.java:81)
        at junit.framework.Assert.assertEquals(Assert.java:87)
        at com.thoughtworks.xstream.io.xml.AbstractXMLReaderTest.testSupportsFieldsWithSpecialCharsInXml11(AbstractXMLReaderTest.java:137)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at junit.framework.TestCase.runTest(TestCase.java:154)
        at junit.framework.TestCase.runBare(TestCase.java:127)
        at junit.framework.TestResult$1.protect(TestResult.java:106)
        at junit.framework.TestResult.runProtected(TestResult.java:124)
        at junit.framework.TestResult.run(TestResult.java:109)
        at junit.framework.TestCase.run(TestCase.java:118)
        at junit.framework.TestSuite.runTest(TestSuite.java:208)
        at junit.framework.TestSuite.run(TestSuite.java:203)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:99)
        at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:140)
        at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:113)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

[ERROR] testISOControlCharactersInValue(com.thoughtworks.xstream.io.xml.StaxReaderTest)  Time elapsed: 0.001 s  <<< ERROR!
com.thoughtworks.xstream.io.StreamException:
        at com.thoughtworks.xstream.io.xml.StaxDriver.createReader(StaxDriver.java:101)
        at com.thoughtworks.xstream.io.xml.AbstractStaxReaderTest.createReader(AbstractStaxReaderTest.java:38)
        at com.thoughtworks.xstream.io.xml.AbstractStaxReaderTest.createReader(AbstractStaxReaderTest.java:34)
        at com.thoughtworks.xstream.io.xml.StaxReaderTest.createReader(StaxReaderTest.java:27)
        at com.thoughtworks.xstream.io.xml.AbstractXMLReaderTest.testISOControlCharactersInValue(AbstractXMLReaderTest.java:154)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at junit.framework.TestCase.runTest(TestCase.java:154)
        at junit.framework.TestCase.runBare(TestCase.java:127)
        at junit.framework.TestResult$1.protect(TestResult.java:106)
        at junit.framework.TestResult.runProtected(TestResult.java:124)
        at junit.framework.TestResult.run(TestResult.java:109)
        at junit.framework.TestCase.run(TestCase.java:118)
        at junit.framework.TestSuite.runTest(TestSuite.java:208)
        at junit.framework.TestSuite.run(TestSuite.java:203)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:99)
        at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:140)
        at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:113)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,19]
Message: only 1.0 is supported as <?xml version not '1.1"?><string>hell'
        at com.bea.xml.stream.MXParser.parseXmlDeclWithVersion(MXParser.java:3280)
        at com.bea.xml.stream.MXParser.parseXmlDecl(MXParser.java:3260)
        at com.bea.xml.stream.MXParser.parsePI(MXParser.java:3102)
        at com.bea.xml.stream.MXParser.parseProlog(MXParser.java:2004)
        at com.bea.xml.stream.MXParser.nextImpl(MXParser.java:1947)
        at com.bea.xml.stream.MXParser.next(MXParser.java:1333)
        at com.bea.xml.stream.MXParser.setInput(MXParser.java:807)
        at com.bea.xml.stream.MXParserFactory.createXMLStreamReader(MXParserFactory.java:261)
        at com.thoughtworks.xstream.io.xml.StaxDriver.createParser(StaxDriver.java:230)
        at com.thoughtworks.xstream.io.xml.StaxDriver.createReader(StaxDriver.java:98)
        ... 26 more
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,19]
Message: only 1.0 is supported as <?xml version not '1.1"?><string>hell'
        at com.bea.xml.stream.MXParser.parseXmlDeclWithVersion(MXParser.java:3280)
        at com.bea.xml.stream.MXParser.parseXmlDecl(MXParser.java:3260)
        at com.bea.xml.stream.MXParser.parsePI(MXParser.java:3102)
        at com.bea.xml.stream.MXParser.parseProlog(MXParser.java:2004)
        at com.bea.xml.stream.MXParser.nextImpl(MXParser.java:1947)
        at com.bea.xml.stream.MXParser.next(MXParser.java:1333)
        at com.bea.xml.stream.MXParser.setInput(MXParser.java:807)
        at com.bea.xml.stream.MXParserFactory.createXMLStreamReader(MXParserFactory.java:261)
        at com.thoughtworks.xstream.io.xml.StaxDriver.createParser(StaxDriver.java:230)
        at com.thoughtworks.xstream.io.xml.StaxDriver.createReader(StaxDriver.java:98)
        ... 26 more

```

**Comment by jtnord** [comment]
nb: also fails with java11 (`11.0.8`)
