### ISSUE TITLE
Warning of use of Unsafe in JDK 23.

### ISSUE THREAD

**Issue by Thihup** [x-stream/xstream#362]
```
WARNING: A terminally deprecated method in sun.misc.Unsafe has been called
WARNING: sun.misc.Unsafe::objectFieldOffset has been called by com.thoughtworks.xstream.converters.reflection.SunUnsafeReflectionProvider (file:/xstream-1.4.20.jar)
WARNING: Please consider reporting this to the maintainers of class com.thoughtworks.xstream.converters.reflection.SunUnsafeReflectionProvider
WARNING: sun.misc.Unsafe::objectFieldOffset will be removed in a future release
```
When running with `--sun-misc-unsafe-memory-access=deny` (the default in the future):

```
java.lang.ExceptionInInitializerError
        at xstream@1.4.20/com.thoughtworks.xstream.core.util.CompositeClassLoader.<clinit>(CompositeClassLoader.java:56)
        at xstream@1.4.20/com.thoughtworks.xstream.XStream.<init>(XStream.java:403)
        at xstream@1.4.20/com.thoughtworks.xstream.XStream.<init>(XStream.java:377)
Caused by: java.lang.UnsupportedOperationException: objectFieldOffset
        at jdk.unsupported/sun.misc.Unsafe.beforeMemoryAccessSlow(Unsafe.java:1826)
        at jdk.unsupported/sun.misc.Unsafe.beforeMemoryAccess(Unsafe.java:1791)
        at jdk.unsupported/sun.misc.Unsafe.objectFieldOffset(Unsafe.java:909)
        at xstream@1.4.20/com.thoughtworks.xstream.converters.reflection.SunUnsafeReflectionProvider.getFieldOffset(SunUnsafeReflectionProvider.java:105)
        at xstream@1.4.20/com.thoughtworks.xstream.converters.reflection.SunUnsafeReflectionProvider.write(SunUnsafeReflectionProvider.java:66)
        at xstream@1.4.20/com.thoughtworks.xstream.converters.reflection.SunUnsafeReflectionProvider.writeField(SunUnsafeReflectionProvider.java:56)
        at xstream@1.4.20/com.thoughtworks.xstream.core.JVM.<clinit>(JVM.java:100)
        ... 30 more
```

Related:
https://openjdk.org/jeps/471

**Comment by Dark-Leader** [comment]
Getting the same warning for JDK 24 and Xstream version 1.4.21
Any updates?

**Comment by hazendaz** [comment]
FYI, `Class.forName(String)` without a classloader can leak classloaders in dynamic/redeployable environments (Jenkins, Maven, etc.). Safer pattern is:

```java
ClassLoader cl = Thread.currentThread().getContextClassLoader();
if (cl == null) cl = XStream.class.getClassLoader();
Class<?> type = Class.forName(className, false, cl);
```

This avoids retention issues while still resolving classes dynamically.

**Comment by yudalang3** [comment]
Yes, this is a significant issue. We kindly ask the developers to pay attention to it and look into whether it can be resolved.

**Comment by long76** [comment]
ping

**Comment by jglick** [comment]
I stumbled across 8c543bfd8569d6430085d8f75033a48277bf20b2 by @joehni but it does not appear to resolve the issue (as described in https://github.com/x-stream/xstream/issues/362#issuecomment-3758620987). I was unable to confirm since it would not compile:

```
xstream/src/java/com/thoughtworks/xstream/core/util/JdkMiscUnsafe.java:[25,36] package jdk.internal.misc does not exist
```

The problem is simple enough to reproduce in `master` (currently a0f1637e977e6f682f483873b5877e6fe18247b8) or `v-1.4.x` (currently 66fcb137355fe2959a383151da9bd7643eb34f15):

```console
$ mvn -V -pl xstream test -Dtest=XStreamTest
Apache Maven 3.9.16 (2bdd9fddda4b155ebf8000e807eb73fd829a51d5)
Maven home: …
Java version: 25.0.3, vendor: Eclipse Adoptium, runtime: …
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.17.…", arch: "amd64", family: "unix"
…
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.thoughtworks.xstream.XStreamTest
WARNING: A terminally deprecated method in sun.misc.Unsafe has been called
WARNING: sun.misc.Unsafe::objectFieldOffset has been called by com.thoughtworks.xstream.converters.reflection.SunUnsafeReflectionProvider (file:/src/gh/x-stream/xstream/xstream/target/classes/)
WARNING: Please consider reporting this to the maintainers of class com.thoughtworks.xstream.converters.reflection.SunUnsafeReflectionProvider
WARNING: sun.misc.Unsafe::objectFieldOffset will be removed in a future release
[INFO] Tests run: 19, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.218 s -- in com.thoughtworks.xstream.XStreamTest
```
