### ISSUE TITLE
ConversionException in custom converter

### ISSUE THREAD

**Issue by dsukhoroslov** [x-stream/xstream#58]
XStream 1.4.9.

```
XStream created as:
	XStream xStream = new XStream(new StaxDriver(new NoNameCoder()));
	xStream.alias("map", java.util.Map.class);
	xStream.registerConverter(new MapConverter());
```
the MapConverter code is:
```
	private static class MapConverter implements Converter {
		
	    private ConcurrentHashMap<String, Class<?>> types = new ConcurrentHashMap<>();
	
	    public boolean canConvert(Class clazz) {
	        return Map.class.isAssignableFrom(clazz);
	    }
	
	    public void marshal(Object value, HierarchicalStreamWriter writer, MarshallingContext context) {
	
	        Map<String, Object> map = (Map<String, Object>) value;
	        for (Map.Entry<String, Object> entry : map.entrySet()) {
	            writer.startNode(entry.getKey());
	            Object val = entry.getValue();
	            if (val != null) {
	            	types.putIfAbsent(entry.getKey(), val.getClass());
	                writer.setValue(val.toString());
	            }
	            writer.endNode();
	        }
	    }
	
	    public Object unmarshal(HierarchicalStreamReader reader, UnmarshallingContext context) {
	
	        Map<String, Object> map = new HashMap<>();
	        while (reader.hasMoreChildren()) {
	            reader.moveDown();
	            String key = reader.getNodeName(); 
	            String val = reader.getValue();
	            Object value = context.convertAnother(val, types.get(key)); // throws exception!
	            map.put(key, value);
	            reader.moveUp();
	        }
	        return map;
	    }
	
	}
```
It works ok on marshaling phase. But at unmarshaling I get the exception:
```
com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : java.lang.IllegalStateException
cause-message       : Current state is not among the states START_ELEMENT , ATTRIBUTEvalid for getAttributeValue()
class               : java.util.HashMap
required-type       : java.util.HashMap
converter-type      : com.bagri.common.util.XMLUtils$MapEntryConverter
path                : /map/boolProp
line number         : 1
version             : 1.4.9
-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1230)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1214)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1085)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1076)
	at com.bagri.common.util.XMLUtils.mapFromXML(XMLUtils.java:216)
	at com.bagri.xdm.cache.hazelcast.impl.DocumentManagementImpl.getDocumentAsMap(DocumentManagementImpl.java:509)
	at com.bagri.xdm.cache.hazelcast.impl.BindDocumentManagementTest.createMapDocumentTest(BindDocumentManagementTest.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.IllegalStateException: Current state is not among the states START_ELEMENT , ATTRIBUTEvalid for getAttributeValue()
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.getAttributeValue(XMLStreamReaderImpl.java:817)
	at com.thoughtworks.xstream.io.xml.StaxReader.getAttribute(StaxReader.java:88)
	at com.thoughtworks.xstream.io.ReaderWrapper.getAttribute(ReaderWrapper.java:52)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:53)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.bagri.common.util.XMLUtils$MapEntryConverter.unmarshal(XMLUtils.java:249)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	... 39 more
```
The exception is caused by StaxDriver, because it is not the right state to explore attributes.
The same code works well if I use DomDriver instead of StaxDriver. But I'd prefer to use the second one. Please have a look.

Thanks, Denis.

**Comment by joehni** [comment]
The behaviour is correct. XStream is based on a stream model and your converter violates this. The DomDriver is not affected, because its underlying source is memory-based, but any stream-based driver will fail. Your converter reads the value of the element, but convertAnother expects the stream to be still at the opening tag of the element. Have a look at the example of the complex converter in the [converter tutorial](http://x-stream.github.io/converter-tutorial.html#ComplexConverter), there's a special remark about this fact.
