### ISSUE TITLE
Error scanJAR unable to open input stream on Websphere 8.5.5 startup with XStream-1.4.8

### ISSUE THREAD

**Issue by dtiller** [x-stream/xstream#7]
When starting a small web app under Websphere 8.5.5 that uses XStream-1.4.8, I get the stacktrace, below. Using XStream-1.4.7 works as expected. 

The exceptions involve the lambda expressions:
scanJAR unable to open input stream for resource com/thoughtworks/xstream/mapper/LambdaMapper.class
unable to open input stream for resource com/thoughtworks/xstream/converters/reflection/LambdaConverter.class

Here's the startup info - it seems to be using Java 1.6.

************ Start Display Current Environment ************
WebSphere Platform 8.5.5.3 [ND 8.5.5.3 cf031430.01][WXS 8.6.0.7 cf71512.19124620] running with process name fakecell-cell4\fakecell4-node1\fake02_1 and process id 3473416
Host Operating System is AIX, version 7.1
Java version = 1.6.0, Java Runtime Version = pap6460_26sr8ifx-20140630_01 (SR8), Java Compiler = j9jit26, Java VM name = IBM J9 VM

```
[5/18/15 14:07:04:268 EDT] 00000077 ecs W com.ibm.ws.ecs.internal.scan.context.impl.ScannerContextImpl scanJAR unable to open input stream for resource com/thoughtworks/xstream/mapper/LambdaMapper.class in archive WEB-INF/lib/xstream-1.4.8.jar
java.lang.IllegalArgumentException
at org.objectweb.asm.ClassReader.<init>(Unknown Source)
at org.objectweb.asm.ClassReader.<init>(Unknown Source)
at org.objectweb.asm.ClassReader.<init>(Unknown Source)
at com.ibm.ws.ecs.internal.scan.impl.ClassScanner.scanInputStream(ClassScanner.java:147)
at com.ibm.ws.ecs.internal.scan.impl.ClassScanner.scanInputStream(ClassScanner.java:124)
at com.ibm.ws.ecs.internal.scan.impl.ClassScanner.scanInputStream(ClassScanner.java:120)
at com.ibm.ws.ecs.internal.scan.context.impl.ScannerContextImpl.scanJAR(ScannerContextImpl.java:275)
at com.ibm.ws.ecs.internal.scan.context.impl.ScannerContextImpl.scanJARs(ScannerContextImpl.java:315)
at com.ibm.ws.ecs.internal.scan.context.impl.WARScannerContext.scanInternal(WARScannerContext.java:76)
at com.ibm.ws.ecs.internal.scan.context.impl.ScannerContextImpl.scan(ScannerContextImpl.java:87)
at com.ibm.ws.ecs.internal.scan.context.impl.ScannerContextImpl.getScannedClasses(ScannerContextImpl.java:70)
at com.ibm.ws.webcontainer.webapp.WebAppImpl.scanForHandlesTypesClasses(WebAppImpl.java:752)
at com.ibm.ws.webcontainer.webapp.WebAppImpl.initializeServletContainerInitializers(WebAppImpl.java:600)
at com.ibm.ws.webcontainer.webapp.WebAppImpl.initialize(WebAppImpl.java:409)
at com.ibm.ws.webcontainer.webapp.WebGroupImpl.addWebApplication(WebGroupImpl.java:88)
at com.ibm.ws.webcontainer.VirtualHostImpl.addWebApplication(VirtualHostImpl.java:169)
at com.ibm.ws.webcontainer.WSWebContainer.addWebApp(WSWebContainer.java:749)
at com.ibm.ws.webcontainer.WSWebContainer.addWebApplication(WSWebContainer.java:634)
at com.ibm.ws.webcontainer.component.WebContainerImpl.install(WebContainerImpl.java:426)
at com.ibm.ws.webcontainer.component.WebContainerImpl.start(WebContainerImpl.java:718)
at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:1177)
at com.ibm.ws.runtime.component.DeployedApplicationImpl.fireDeployedObjectStart(DeployedApplicationImpl.java:1370)
at com.ibm.ws.runtime.component.DeployedModuleImpl.start(DeployedModuleImpl.java:639)
at com.ibm.ws.runtime.component.DeployedApplicationImpl.start(DeployedApplicationImpl.java:968)
at com.ibm.ws.runtime.component.ApplicationMgrImpl.startApplication(ApplicationMgrImpl.java:776)
at com.ibm.ws.runtime.component.ApplicationMgrImpl$5.run(ApplicationMgrImpl.java:2195)
at com.ibm.ws.security.auth.ContextManagerImpl.runAs(ContextManagerImpl.java:5474)
at com.ibm.ws.security.auth.ContextManagerImpl.runAsSystem(ContextManagerImpl.java:5600)
at com.ibm.ws.security.core.SecurityContext.runAsSystem(SecurityContext.java:255)
at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:2200)
at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:389)
at com.ibm.ws.runtime.component.CompositionUnitImpl.start(CompositionUnitImpl.java:123)
at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:332)
at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.access$500(CompositionUnitMgrImpl.java:119)
at com.ibm.ws.runtime.component.CompositionUnitMgrImpl$CUInitializer.run(CompositionUnitMgrImpl.java:938)
at com.ibm.wsspi.runtime.component.WsComponentImpl$_AsynchInitializer.run(WsComponentImpl.java:502)
at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1864)

[5/18/15 14:07:04:293 EDT] 00000077 ecs W com.ibm.ws.ecs.internal.scan.context.impl.ScannerContextImpl scanJAR unable to open input stream for resource com/thoughtworks/xstream/converters/reflection/LambdaConverter.class in archive WEB-INF/lib/xstream-1.4.8.jar
java.lang.IllegalArgumentException
at org.objectweb.asm.ClassReader.<init>(Unknown Source)
at org.objectweb.asm.ClassReader.<init>(Unknown Source)
at org.objectweb.asm.ClassReader.<init>(Unknown Source)
at com.ibm.ws.ecs.internal.scan.impl.ClassScanner.scanInputStream(ClassScanner.java:147)
at com.ibm.ws.ecs.internal.scan.impl.ClassScanner.scanInputStream(ClassScanner.java:124)
at com.ibm.ws.ecs.internal.scan.impl.ClassScanner.scanInputStream(ClassScanner.java:120)
at com.ibm.ws.ecs.internal.scan.context.impl.ScannerContextImpl.scanJAR(ScannerContextImpl.java:275)
at com.ibm.ws.ecs.internal.scan.context.impl.ScannerContextImpl.scanJARs(ScannerContextImpl.java:315)
at com.ibm.ws.ecs.internal.scan.context.impl.WARScannerContext.scanInternal(WARScannerContext.java:76)
at com.ibm.ws.ecs.internal.scan.context.impl.ScannerContextImpl.scan(ScannerContextImpl.java:87)
at com.ibm.ws.ecs.internal.scan.context.impl.ScannerContextImpl.getScannedClasses(ScannerContextImpl.java:70)
at com.ibm.ws.webcontainer.webapp.WebAppImpl.scanForHandlesTypesClasses(WebAppImpl.java:752)
at com.ibm.ws.webcontainer.webapp.WebAppImpl.initializeServletContainerInitializers(WebAppImpl.java:600)
at com.ibm.ws.webcontainer.webapp.WebAppImpl.initialize(WebAppImpl.java:409)
at com.ibm.ws.webcontainer.webapp.WebGroupImpl.addWebApplication(WebGroupImpl.java:88)
at com.ibm.ws.webcontainer.VirtualHostImpl.addWebApplication(VirtualHostImpl.java:169)
at com.ibm.ws.webcontainer.WSWebContainer.addWebApp(WSWebContainer.java:749)
at com.ibm.ws.webcontainer.WSWebContainer.addWebApplication(WSWebContainer.java:634)
at com.ibm.ws.webcontainer.component.WebContainerImpl.install(WebContainerImpl.java:426)
at com.ibm.ws.webcontainer.component.WebContainerImpl.start(WebContainerImpl.java:718)
at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:1177)
at com.ibm.ws.runtime.component.DeployedApplicationImpl.fireDeployedObjectStart(DeployedApplicationImpl.java:1370)
at com.ibm.ws.runtime.component.DeployedModuleImpl.start(DeployedModuleImpl.java:639)
at com.ibm.ws.runtime.component.DeployedApplicationImpl.start(DeployedApplicationImpl.java:968)
at com.ibm.ws.runtime.component.ApplicationMgrImpl.startApplication(ApplicationMgrImpl.java:776)
at com.ibm.ws.runtime.component.ApplicationMgrImpl$5.run(ApplicationMgrImpl.java:2195)
at com.ibm.ws.security.auth.ContextManagerImpl.runAs(ContextManagerImpl.java:5474)
at com.ibm.ws.security.auth.ContextManagerImpl.runAsSystem(ContextManagerImpl.java:5600)
at com.ibm.ws.security.core.SecurityContext.runAsSystem(SecurityContext.java:255)
at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:2200)
at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:389)
at com.ibm.ws.runtime.component.CompositionUnitImpl.start(CompositionUnitImpl.java:123)
at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:332)
at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.access$500(CompositionUnitMgrImpl.java:119)
at com.ibm.ws.runtime.component.CompositionUnitMgrImpl$CUInitializer.run(CompositionUnitMgrImpl.java:938)
at com.ibm.wsspi.runtime.component.WsComponentImpl$_AsynchInitializer.run(WsComponentImpl.java:502)
at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1864)

```

**Comment by joehni** [comment]
XStream 1.4.8 contains some classes targeting Java 8 which are only used in a Java 8 runtime environment. In your case you can simply remove the LambdaConverter and LambdaMapper from the jar file.

**Comment by dtiller** [comment]
Jörg,

Mutilating a jar based on the JVM revision is hardly a valid solution. Remember write once, run everywhere? Perhaps better detection of the JVM vendor/version in the XStream code would allow the complete jar to be used on all systems.

The XStream-1.4.8 jar works fine under websphere 7.0, just not websphere 8.5.5.


--
David Tiller
Sr. Architect/Lead Consultant | CapTech
(804) 304-0638 | dtiller@captechconsulting.com<mailto:dtiller@captechconsulting.com>



On May 19, 2015, at 5:22 PM, Jörg Schaible <notifications@github.com<mailto:notifications@github.com>> wrote:


XStream 1.4.8 contains some classes targeting Java 8 which are only used in a Java 8 runtime environment. In your case you can simply remove the LambdaConverter and LambdaMapper from the jar file.

**Comment by joehni** [comment]
XStream has a very long history of mixed class files ... more than 10 years since XStream 1.1.2. The question is, why your environment tries to load class files although they are not accessed. The original jar file can normally be used even in Java 1.4 environment.

**Comment by dtiller** [comment]
You wrote: "The question is, why your environment tries to load class files although they are not accessed. "

Now THAT is the real question. My guess would be the that the Java-EE annotation scanning that happens on startup of Java-EE apps is failing catastrophically. Does the XStream-1.4.8 jar have any annotations, or would disallowing scanning of your package break XStream's functionality? I can test filtering out your package via entries in the manifest. See http://www-01.ibm.com/support/knowledgecenter/SSEQTP_8.5.5/com.ibm.websphere.base.doc/ae/trun_app_reduce_annot.html?cp=SSEQTP_8.5.5%2F1-8-2-11-0

If that works, perhaps you could add those properties so that no WAS server scans your jars.

Thanks for the replies!

**Comment by joehni** [comment]
Hmm. According the JEE specs you have to add a bean.xml into the META-INF of your jar for CDI scanning. XStream itself provides own annotations, but does not even use them internally. JEE scanning makes no sense for XStream.

**Comment by joehni** [comment]
Did you make any progress?

**Comment by rodrik** [comment]
Recently I've got the same problem here. @dtiller any news?

**Comment by dtiller** [comment]
I have not been able to test it at the client. My test would've been to add the proper value to the xstream.jar's manifest as described here: http://www-304.ibm.com/support/docview.wss?rs=180&uid=swg1PK87053 and here: http://www-01.ibm.com/support/knowledgecenter/SSAW57_8.0.0/com.ibm.websphere.nd.doc/info/ae/ae/trun_app_reduce_annot.html?cp=SSAW57_8.0.0%2F1-8-12-0

Something like this: Ignore-Scanning-Packages : com.thoughtworks.xstream


That should disable the annotation processing for the xstream jar and allow it to be deployed properly.

**Comment by joehni** [comment]
Next XStream release will have an entry in the FAQ.
