### ISSUE TITLE
Cascading writeReplace() methods creates invalid xml (duplicate resolves-to)

### ISSUE THREAD

**Issue by rscadrde** [x-stream/xstream#76]
When using toXml() on a JPA list there maybe to delegates for list which let
XStream create a duplicate attribute "resolves-to":
`<org.apache.openjpa.kernel.DelegatingResultList resolves-to="org.apache.openjpa.lib.rop.EagerResultList" resolves-to="list">
`
using fromXml then fails with

```
com.thoughtworks.xstream.io.StreamException: 
    at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:124)
    at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148)
    at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:141)
    at com.thoughtworks.xstream.io.xml.AbstractPullReader.move(AbstractPullReader.java:118)
    at com.thoughtworks.xstream.io.xml.AbstractPullReader.moveDown(AbstractPullReader.java:103)
    at com.thoughtworks.xstream.io.xml.XppReader.<init>(XppReader.java:63)
    at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:54)
    at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1085)
    at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1076)
Caused by: org.xmlpull.v1.XmlPullParserException: duplicated attributes resolves-to and resolves-to (position: START_DOCUMENT seen ...o="org.apache.openjpa.lib.rop.EagerResultList" resolves-to="list">... @1:124) 
    at org.xmlpull.mxp1.MXParser.parseStartTag(MXParser.java:1891)
    at org.xmlpull.mxp1.MXParser.parseProlog(MXParser.java:1479)
    at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1395)
    at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
    at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:109)
```

Here is a short test failing on xstream 1.4.9: XStream149Test.java in 
[XStream149Test.zip](https://github.com/x-stream/xstream/files/556851/XStream149Test.zip)

**Comment by rscadrde** [comment]
org.xmlpull.mxp1.MXParser comes out of our dependency xpp3_min-1.1.4c.jar

**Comment by rscadrde** [comment]
With kxml2-min the error does not come up.

**Comment by rscadrde** [comment]
When you remove

    <dependency>
      <groupId>net.sf.kxml</groupId>
      <artifactId>kxml2-min</artifactId>
      <optional>true</optional>
    </dependency>

    <dependency>
      <groupId>net.sf.kxml</groupId>
      <artifactId>kxml2</artifactId>
      <optional>true</optional>
    </dependency>

out of the pom.xml the test out of the pull request fails as expected.

**Comment by joehni** [comment]
Thanks for the test and fix. As you've already found out, it had nothing to do with the XML parser dependencies. Actually, I never thought about a cascaded writeReplace ...
