### ISSUE TITLE
XSteam 1.4.9 is not work with jdk1.4

### ISSUE THREAD

**Issue by ddknight** [x-stream/xstream#97]
> org.apache.jasper.JasperException: com/thoughtworks/xstream/XStream (Unsupported major.minor version 49.0)
	at org.apache.jasper.servlet.JspServletWrapper.service(Unknown Source)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(Unknown Source)
	at org.apache.jasper.servlet.JspServlet.service(Unknown Source)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Unknown Source)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(Unknown Source)
	at org.apache.catalina.core.StandardWrapperValve.invoke(Unknown Source)
	at org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(Unknown Source)
	at org.apache.catalina.core.StandardPipeline.invoke(Unknown Source)
	at org.apache.catalina.core.ContainerBase.invoke(Unknown Source)
	at org.apache.catalina.core.StandardContextValve.invoke(Unknown Source)
	at org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(Unknown Source)
	at org.jboss.web.tomcat.security.JBossSecurityMgrRealm.invoke(Unknown Source)
	at org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(Unknown Source)
	at org.apache.catalina.valves.CertificatesValve.invoke(Unknown Source)
	at org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(Unknown Source)
	at org.jboss.web.tomcat.tc4.statistics.ContainerStatsValve.invoke(Unknown Source)
	at org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(Unknown Source)
	at org.apache.catalina.core.StandardPipeline.invoke(Unknown Source)
	at org.apache.catalina.core.ContainerBase.invoke(Unknown Source)
	at org.apache.catalina.core.StandardContext.invoke(Unknown Source)
	at org.apache.catalina.core.StandardHostValve.invoke(Unknown Source)
	at org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(Unknown Source)
	at org.apache.catalina.valves.ErrorDispatcherValve.invoke(Unknown Source)
	at org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(Unknown Source)
	at org.apache.catalina.valves.ErrorReportValve.invoke(Unknown Source)
	at org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(Unknown Source)
	at org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(Unknown Source)
	at org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(Unknown Source)
	at org.apache.catalina.valves.AccessLogValve.invoke(Unknown Source)
	at org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(Unknown Source)
	at org.apache.catalina.core.StandardPipeline.invoke(Unknown Source)
	at org.apache.catalina.core.ContainerBase.invoke(Unknown Source)
	at org.apache.catalina.core.StandardEngineValve.invoke(Unknown Source)
	at org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(Unknown Source)
	at org.apache.catalina.core.StandardPipeline.invoke(Unknown Source)
	at org.apache.catalina.core.ContainerBase.invoke(Unknown Source)
	at org.apache.coyote.tomcat4.CoyoteAdapter.service(Unknown Source)
	at org.apache.coyote.http11.Http11Processor.process(Unknown Source)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.processConnection(Unknown Source)
	at org.apache.tomcat.util.net.TcpWorkerThread.runIt(PoolTcpEndpoint.java:605)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:677)
	at java.lang.Thread.run(Thread.java:534)
When I run my application, started with Jboss 3.2.3.GA,I got this error message out.

But,I found this in the xstream's site.http://x-stream.github.io/faq.html

> Which Java runtime is required to run XStream?
XStream 1.4.x requires Java 1.4 or later. Note, that the XStream libraries contains class files targeting different Java runtime versions or Java features. These classes are loaded by reflection and only used if XStream is running on an appropriate runtime environment.

so,which java runtime is really work with xstream 1.4.x,or which version is completed work with jdk1.4?
I am confused.

**Comment by joehni** [comment]
This support is currently not out of the box (see [Release Notes for XStream 1.4.2](http://x-stream.github.io/changes.html#1.4.2)). For now you will have to download the distribution [sources](http://search.maven.org/remotecontent?filepath=com/thoughtworks/xstream/xstream-distribution/1.4.10/xstream-distribution-1.4.10-src.zip) and build it with Maven 2.0.11 and a JDK 1.4 yourself. I use myself Blackdown JDK 1.4 for test.

However, I managed to setup the build now in a way that the target JDK is again 1.4 for all classes used in a Java 1.4 runtime. This will be available with the next XStream release.
